### ISSUE TITLE
Doesn't seem to work without HTML

### ISSUE THREAD

**Issue by watzon** [luckyframework/carbon_smtp_adapter#14]
Tried creating an Email class that only included a text format and things broke:

```
In lib/carbon/src/carbon/email.cr:137:35

 137 | response = settings.adapter.deliver_now(self)
                                   ^----------
Error: instantiating 'Carbon::Adapter+#deliver_now(DeleteCommentEmail)'


In lib/carbon_smtp_adapter/src/carbon/adapters/smtp_adapter.cr:15:13

 15 | ::EMail.send(settings.host, settings.port, auth: auth, use_tls: use_tls) do
              ^---
Error: instantiating 'EMail:Module#send(String, Int32)'


In lib/carbon_smtp_adapter/src/carbon/adapters/smtp_adapter.cr:15:13

 15 | ::EMail.send(settings.host, settings.port, auth: auth, use_tls: use_tls) do
              ^---
Error: instantiating 'EMail:Module#send(String, Int32)'


In lib/carbon_smtp_adapter/src/carbon/adapters/smtp_adapter.cr:48:26

 48 | message_html email.html_body
                         ^--------
Error: expected argument luckyframework/carbon_smtp_adapter#1 to 'Carbon::SmtpAdapter#message_html' to be String, not Nil
```

**Comment by jwoertink** [comment]
In the email, the templates had just `templates text`?  This is probably a [Carbon](https://github.com/luckyframework/carbon)  related issue, so I'll transfer it over there.

**Comment by matthewmcgarvey** [comment]
The issue is actually in the [carbon_smtp_adapter](https://github.com/luckyframework/carbon_smtp_adapter) shard.

Thie `message_html email.html_body` needs to be wrapped in an if block to only call `message_html` if `email.html_body` is not nil.

https://github.com/luckyframework/carbon_smtp_adapter/blob/a989b6a7421f994ded4d83d3ecf87cb11fc895c7/src/carbon/adapters/smtp_adapter.cr#L48

**Comment by jwoertink** [comment]
ohhh! Oops. Good find. I guess we can move it back :joy:
